### ISSUE TITLE
Allow for glob pattern in URLs to block

### ISSUE THREAD

**Issue by gDelgado14** [raicem/impulse-blocker#14]
It would be nice if I could block some portions of a website while still allowing for access to others. 

Reddit is a good example. 

I would like to block `reddit.com/r/funny*` (everything in the `/r/funny` subreddit - including threads and posts)

This is useful because I have not blocked all of reddit. Just the `/r/funny` subreddit and any threads inside it.

**Comment by Crote** [comment]
If I'm not mistaken, globs are already (mostly) supported. [This line](https://github.com/raicem/impulse-blocker/blob/master/background.js#L54) defines the [match patterns](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns) created for the filter. Note that `reddit.com/r/funny*` would be expanded to `*://*.reddit.com/r/funny*/*`, which would block everything as expected. You would't even need to specify the blob, as `reddit.com/r/funny` expands to `*://*.reddit.com/r/funny/*`.

So why doesn't it work when you add it in the settings? Because [this line](https://github.com/raicem/impulse-blocker/blob/master/options/options.js#L48) uses `url.hostname` instead of plain `url` when blocking the entered url. This is the right behaviour when [blocking from the button popup](https://github.com/raicem/impulse-blocker/blob/master/background.js#L138), but in this case it stops the glob from working as it should.

**Comment by raicem** [comment]
Thanks to @Crote's work, now you can add `reddit.com/r/funny*` to block certain subreddits. I have merged the pull request and upload the upload today. Thanks @Crote
