### ISSUE TITLE
ImpulseBlocker doesn't automatically start in a new private browsing session

### ISSUE THREAD

**Issue by Octillerysnacker** [raicem/impulse-blocker#21]
Basically just open a new private session and none of the blocked websites are blocked. Another weird note is that the On/Off options for the addon have neither option selected.

**Comment by prail** [comment]
This happens with any Firefox extension when you open Firefox in privacy mode. You can add an exception in FF's extension privacy settings if you'd like.

**Comment by raicem** [comment]
I could not replicate the part about currently blocked websites are not being blocked in the private session. Using Firefox 63. They are still blocked when I switch to the private mode.

You are definitely right about the on/off options being unselected. This is due to the fact that we can't access the background process of the extension so we can get extension status, we can not get the url, we can not add or remove sites from the toolbar/popup. The workaround is cumbersome. Until that time I think I should add a warning about it. 

You can still control anything from the non-private windows and they are reflected immediately to the private session.

**Comment by raicem** [comment]
This should be solved with 1.0.0 release.
