### ISSUE TITLE
[WIP] New configuration page

### ISSUE THREAD

**Issue by Crote** [raicem/impulse-blocker#32]
![screen shot 2018-12-07 at 16 37 40](https://user-images.githubusercontent.com/931757/49656909-c54eeb00-fa3e-11e8-9d4e-d7d9f8038c42.png)
The current settings page is, to put it mildly, not exactly ideal. I've been working on a mockup using [Bootswatch Lux](https://bootswatch.com/lux/) which incorporates #28, #27, a very minor version of #13, and a better start for #9.

@raicem , what are your thoughts on this? Is this approach something worth pursuing? The same style could also be used for the block page.

**Comment by raicem** [comment]
Current settings page is as it is because initially Firefox would show these options in the extensions page.
![resim](https://user-images.githubusercontent.com/10389957/50667889-a192ac80-0fcc-11e9-8bf3-880342d89942.png)
But now it opens it up in a new blank page, giving us a huge opportunity. You have done a great job, so thank you very much. Design is much simpler to implement than the other advanced features you have mentioned. I will definately tackle that in upcoming weeks.

**Comment by raicem** [comment]
Hi @Crote, new settings page is done with the 1.0.0 update. It is live now. Many thanks for the design. I would be lost without it. Hope you like it!

**Comment by Crote** [comment]
Ooh, that's very nice. I definitely like it!
